import 'package:siptatif_app/datas/models/mahasiswa.dart';

List<Mahasiswa> mahasiswaData = [
  Mahasiswa(
      jenisPendaftaran: "Individu",
      nama: "M. Farhan Aulia Pratama",
      NIM: "12250113521",
      email: "farhanaulia.p@gmail.com",
      judulTugasAkhir: "Rancang Bangun Sistem SIPTATIF",
      kategoriTugasAkhir: "Laporan",
      calonDosenPembimbing1: "Dr. Fulanah, S.T, M.Kom,.",
      calonDosenPembimbing2: "Dr. Fulanah, S.T, M.Kom,.",
      berkas: "assets/berkas/12250113521.pdf",
      statusBerkas: "Disetujui",
      catatanUntukMahasiswa: "Sudah Bagus",
  ),
  Mahasiswa(
    jenisPendaftaran: "Individu",
    nama: "M. Farhan Aulia Pratama",
    NIM: "12250113521",
    email: "farhanaulia.p@gmail.com",
    judulTugasAkhir: "Rancang Bangun Sistem SIPTATIF",
    kategoriTugasAkhir: "Laporan",
    calonDosenPembimbing1: "Dr. Fulanah, S.T, M.Kom,.",
    calonDosenPembimbing2: "Dr. Fulanah, S.T, M.Kom,.",
    berkas: "assets/berkas/12250113521.pdf",
    statusBerkas: "Ditolak",
    catatanUntukMahasiswa: "Sudah Bagus",
  ),
  Mahasiswa(
    jenisPendaftaran: "Individu",
    nama: "M. Farhan Aulia Pratama",
    NIM: "12250113521",
    email: "farhanaulia.p@gmail.com",
    judulTugasAkhir: "Rancang Bangun Sistem SIPTATIF",
    kategoriTugasAkhir: "Laporan",
    calonDosenPembimbing1: "Dr. Fulanah, S.T, M.Kom,.",
    calonDosenPembimbing2: "Dr. Fulanah, S.T, M.Kom,.",
    berkas: "assets/berkas/12250113521.pdf",
    statusBerkas: "Menunggu",
    catatanUntukMahasiswa: "Sudah Bagus",
  ),
  Mahasiswa(
    jenisPendaftaran: "Individu",
    nama: "M. Farhan Aulia Pratama",
    NIM: "12250113521",
    email: "farhanaulia.p@gmail.com",
    judulTugasAkhir: "Rancang Bangun Sistem SIPTATIF",
    kategoriTugasAkhir: "Laporan",
    calonDosenPembimbing1: "Dr. Fulanah, S.T, M.Kom,.",
    calonDosenPembimbing2: "Dr. Fulanah, S.T, M.Kom,.",
    berkas: "assets/berkas/12250113521.pdf",
    statusBerkas: "Ditolak",
    catatanUntukMahasiswa: "Sudah Bagus",
  ),
  Mahasiswa(
    jenisPendaftaran: "Individu",
    nama: "M. Farhan Aulia Pratama",
    NIM: "12250113521",
    email: "farhanaulia.p@gmail.com",
    judulTugasAkhir: "Rancang Bangun Sistem SIPTATIF",
    kategoriTugasAkhir: "Laporan",
    calonDosenPembimbing1: "Dr. Fulanah, S.T, M.Kom,.",
    calonDosenPembimbing2: "Dr. Fulanah, S.T, M.Kom,.",
    berkas: "assets/berkas/12250113521.pdf",
    statusBerkas: "Disetujui",
    catatanUntukMahasiswa: "Sudah Bagus",
  ),
];
